-- Migration 023: seed CMS copy previously embedded in frontend fallbacks.
-- Existing site content wins; only absent keys are initialized.
SET NAMES utf8mb4;
START TRANSACTION;
INSERT IGNORE INTO site_content (content_key, content_value)
VALUES
  ('activities_4x4_eyebrow', 'Lagos Off-Road, Tor y Pic Negre'),
  ('activities_4x4_title', '4×4'),
  ('activities_bike_eyebrow', 'Enduro, E-Bike, BTT y remontes'),
  ('activities_bike_title', 'Bike'),
  ('activities_esqui_eyebrow', 'Raquetas y esquí tour'),
  ('activities_esqui_title', 'Esquí-Snow'),
  ('activities_holiday_eyebrow', 'Paquetes y escapadas en la nieve'),
  ('activities_senderismo_eyebrow', 'Medio día y día completo'),
  ('activities_senderismo_title', 'Senderismo'),
  ('activities_via_ferrata_eyebrow', 'Iniciación y avanzado'),
  ('activities_via_ferrata_title', 'Vía Ferrata'),
  ('calendar_events_label', 'Eventos'),
  ('calendar_events_name', 'Team Building & Eventos Deportivos'),
  ('calendar_events_place', 'Andorra'),
  ('calendar_holiday_label', 'Holiday'),
  ('contact_address', 'Av. de Sant Antoni, 12, AD400 La Massana, Andorra'),
  ('contact_copy', 'Recibe novedades, disponibilidad de actividades y un poco de inspiración para tu próxima aventura. Sin ruido. Solo lo bueno.'),
  ('contact_eyebrow', 'Mantente inspirado'),
  ('contact_phone', '+376 653 769'),
  ('contact_title_line1', 'Más montaña.'),
  ('contact_title_line2', 'Menos rutina.'),
  ('contact_whatsapp_link', 'O escríbenos directamente'),
  ('footer_brand_desc', 'Turismo activo y experiencias de montaña en Andorra y los Pirineos.'),
  ('footer_nav_heading', 'Navegación'),
  ('footer_social_desc', 'Conéctate con nuestra comunidad en la montaña:'),
  ('footer_social_heading', 'Síguenos'),
  ('hero_cta_activities', 'Ver actividades'),
  ('hero_cta_reserve', 'Reservar ahora'),
  ('hero_eyebrow', 'Elige tu experiencia con nosotros'),
  ('hero_scroll_hint', 'Descubre más'),
  ('hero_tagline', 'Fabricamos experiencias.'),
  ('hero_title_line1', 'Todas las experiencias.'),
  ('hero_title_line2', 'Un solo operador.'),
  ('logo_height', '44'),
  ('mission_eyebrow', 'Nuestra empresa'),
  ('mission_image', 'https://i-wildland.com/wp-content/uploads/2020/04/roc-del-quer-2.jpg'),
  ('mission_stat1_label', 'año de fundación'),
  ('mission_stat1_value', '2018'),
  ('mission_stat2_label', 'tipos de actividades'),
  ('mission_stat2_value', '15+'),
  ('mission_stat3_label', 'regiones: Andorra y Pirineos'),
  ('mission_stat3_value', '2'),
  ('mission_team_link', 'Nuestro equipo'),
  ('mission_text', 'Descubre un mundo de experiencias únicas con un solo operador turístico. Esquí, snowboard, raquetas de nieve, tours culturales y todo lo que te puedas imaginar para vivir la montaña, guiado por expertos locales como Charly Paredes.'),
  ('news_detail_back_link', 'Volver a novedades'),
  ('news_detail_cta_button', 'Contactar a un guía'),
  ('news_detail_cta_eyebrow', '¿Te inspiró esta experiencia?'),
  ('news_detail_cta_title', 'Planifica tu aventura con nosotros'),
  ('news_detail_eyebrow', 'Novedades iWE'),
  ('news_detail_loading', 'Cargando publicación...'),
  ('news_detail_not_found_copy', 'La noticia que buscas no existe o ha sido despublicada.'),
  ('news_detail_not_found_title', 'Publicación no encontrada'),
  ('news_detail_see_all', 'Ver todas las novedades'),
  ('news_detail_social_facebook', '📘 Ver en Facebook'),
  ('news_detail_social_instagram', '📷 Ver en Instagram'),
  ('news_detail_social_title', 'Ver también en redes'),
  ('news_list_back_home', 'Volver al inicio'),
  ('news_list_contact_cta', 'Contactar con nosotros'),
  ('news_list_copy', 'Descubre las últimas noticias, estados de senderos, consejos técnicos y relatos de nuestras expediciones en Andorra y los Pirineos.'),
  ('news_list_empty_copy', 'Estamos preparando nuevas historias y reportes de temporada. ¡Vuelve a visitarnos pronto!'),
  ('news_list_empty_title', 'Próximamente nuevas publicaciones'),
  ('news_list_explore_cta', 'Explorar actividades'),
  ('news_list_eyebrow', 'Actualidad & Rutas'),
  ('news_list_loading', 'Cargando novedades...'),
  ('news_list_title', 'Novedades de la montaña'),
  ('newsletter_email_label', 'Tu correo electrónico'),
  ('newsletter_success_message', 'Ya formas parte de la lista. Nos vemos en la montaña.'),
  ('reviews_direct_published', 'true'),
  ('reviews_eyebrow', 'Opiniones de clientes'),
  ('reviews_google_published', 'true'),
  ('reviews_tab_all', 'Todas'),
  ('reviews_tab_direct', 'iWE'),
  ('reviews_tab_google', 'Google ★ 4.9'),
  ('reviews_tab_tripadvisor', 'TripAdvisor ★ 5.0'),
  ('reviews_tripadvisor_published', 'true'),
  ('site_url', 'https://i-wildland.com'),
  ('social_facebook', 'https://www.facebook.com/isardwildland/'),
  ('social_instagram', 'https://www.instagram.com/isardwildland/'),
  ('social_tripadvisor', 'https://www.tripadvisor.com/'),
  ('team_bio', 'iWE nació en 2018 de la mano de Charly Paredes, guía de montaña nivel 2 (EFPEM Andorra), instructor de esquí certificado por AADIDES/ISIA y miembro de UIMLA y AGAMA. Formado entre Ushuaia y Andorra, habla catalán, español, francés e inglés.

Cada ruta está pensada para adaptarse a tu nivel físico y técnico, sea que viajes en familia, en pareja o con amigos. Tú pones la curiosidad. Nosotros nos ocupamos del resto.'),
  ('team_contact_link', 'Cómo trabajamos'),
  ('team_eyebrow', 'Nuestro equipo'),
  ('team_image', 'https://i-wildland.com/wp-content/uploads/2022/07/FSF-49-1024x683-iWE.jpg'),
  ('team_image_note_line1', 'Conocimiento local.'),
  ('team_image_note_line2', 'Experiencia real.'),
  ('team_title', 'Fundada en 2018. Guiada por expertos locales.'),
  ('tour_detail_consult_price', 'Consultar precio'),
  ('tour_detail_distance', 'Distancia'),
  ('tour_detail_duration', 'Duración'),
  ('tour_detail_elevation', 'Desnivel'),
  ('tour_detail_highlights', 'Qué incluye / Puntos destacados'),
  ('tour_detail_itinerary', 'Itinerario'),
  ('tour_detail_level', 'Nivel'),
  ('tour_detail_location', 'Ubicación'),
  ('tour_detail_min_age', 'Edad mínima'),
  ('tour_detail_price', 'Precio'),
  ('tour_detail_related_title', 'También te puede interesar'),
  ('tour_detail_reserve_cta', 'Reservar esta experiencia'),
  ('tour_hero_scroll_hint', 'Descubre más'),
  ('tour_share_title', 'Compartir experiencia'),
  ('tours_copy', 'Combina alojamiento, guías y actividades en un solo paquete. Ideal para grupos, familias y viajes de aventura sin preocuparte por la logística.'),
  ('tours_cta_text', 'Consultar disponibilidad'),
  ('tours_eyebrow', 'Tours en Andorra'),
  ('tours_section_published', 'true'),
  ('tours_title_line1', 'Vacaciones'),
  ('tours_title_line2', 'completas con iWE.'),
  ('weather_copy', 'Previsión meteorológica y mapa interactivo de viento en directo para planificar tus salidas de BTT, senderismo o esquí con la máxima seguridad.'),
  ('weather_eyebrow', 'Condiciones en tiempo real'),
  ('weather_map_lat', '42.5459743'),
  ('weather_map_lon', '1.5140217'),
  ('weather_meta_badge', 'Viento & Previsión en vivo'),
  ('weather_meta_location', 'Andorra (42.55° N, 1.51° E) • Modelo ECMWF'),
  ('weather_title_line1', 'El tiempo en Andorra'),
  ('weather_title_line2', 'y los Pirineos.');
UPDATE menu_items
SET link_type = 'anchor', target_value = '/#andorra-holiday-snow'
WHERE id = 40 AND link_type = 'route' AND target_value = '/';
COMMIT;
