<?php
/**
 * iWE Dashboard API - API Keys Storage Service
 * 
 * Handles atomic persistence of configuration overrides in config.local.php,
 * outside version control, with tempnam + rename for concurrency protection.
 */

declare(strict_types=1);

require_once __DIR__ . '/ApiKeysMasker.php';

class ApiKeysStorage {
    private string $localConfigFile;

    public function __construct(?string $localConfigFile = null) {
        $this->localConfigFile = $localConfigFile ?? (__DIR__ . '/../../config/config.local.php');
    }

    public function getStorageFilePath(): string {
        return $this->localConfigFile;
    }

    public function isWritable(): bool {
        $configDir = dirname($this->localConfigFile);
        return is_writable($configDir) && (!file_exists($this->localConfigFile) || is_writable($this->localConfigFile));
    }

    public function readLocalConfigFile(): array {
        if (file_exists($this->localConfigFile)) {
            $data = require $this->localConfigFile;
            if (is_array($data)) {
                return $data;
            }
        }
        return [];
    }

    public function writeLocalConfigFile(array $data): void {
        $dir = dirname($this->localConfigFile);
        if (!is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $content = "<?php\n/**\n * iWE Dashboard - Local Configuration & API Keys Override\n * Auto-generated by ApiKeysController\n */\n\nreturn " . var_export($data, true) . ";\n";

        // Atomic write: temp file + rename
        $tempFile = tempnam($dir, 'cfg_tmp_');
        if ($tempFile === false) {
            jsonError('No se pudo crear el archivo temporal de configuración.', 500);
        }

        if (file_put_contents($tempFile, $content) === false) {
            @unlink($tempFile);
            jsonError('Error al escribir el archivo temporal de configuración.', 500);
        }

        chmod($tempFile, 0644);

        if (!rename($tempFile, $this->localConfigFile)) {
            @unlink($tempFile);
            jsonError('Error al reemplazar el archivo de configuración atómico.', 500);
        }
    }

    public function saveKey(string $keyName, string $value, string $description = ''): array {
        $isStandard = ApiKeysMasker::isStandardKey($keyName);
        if (!$isStandard && !ApiKeysMasker::isValidCustomKeyName($keyName)) {
            jsonError('El nombre de la variable personalizada no es válido. Debe usar mayúsculas, números o guiones bajos (ej: TELEGRAM_BOT_TOKEN).', 422);
        }

        $localData = $this->readLocalConfigFile();

        if ($isStandard) {
            [$section, $prop] = ApiKeysMasker::STANDARD_KEYS_MAP[$keyName];
            if (!isset($localData[$section]) || !is_array($localData[$section])) {
                $localData[$section] = [];
            }
            $localData[$section][$prop] = $value;
        } else {
            if (!isset($localData['custom_keys']) || !is_array($localData['custom_keys'])) {
                $localData['custom_keys'] = [];
            }
            $localData['custom_keys'][$keyName] = [
                'value'       => $value,
                'description' => $description,
                'updated_at'  => date('Y-m-d H:i:s'),
            ];
        }

        $this->writeLocalConfigFile($localData);

        return [
            'key_name'      => $keyName,
            'is_configured' => !empty($value),
            'masked_value'  => ApiKeysMasker::maskValue($value),
        ];
    }

    public function deleteCustomKey(string $keyName): void {
        if (ApiKeysMasker::isStandardKey($keyName)) {
            jsonError('Las credenciales estándar del sistema no pueden eliminarse, únicamente vaciarse.', 400);
        }

        $localData = $this->readLocalConfigFile();
        if (isset($localData['custom_keys'][$keyName])) {
            unset($localData['custom_keys'][$keyName]);
            $this->writeLocalConfigFile($localData);
            jsonSuccess(null, "Credencial '{$keyName}' eliminada correctamente.");
        } else {
            jsonError("La credencial '{$keyName}' no existe.", 404);
        }
    }

    public function formatCustomKeys(array $localData): array {
        $customKeys = [];
        if (!empty($localData['custom_keys']) && is_array($localData['custom_keys'])) {
            foreach ($localData['custom_keys'] as $name => $item) {
                $val = is_array($item) ? ($item['value'] ?? '') : (string)$item;
                $desc = is_array($item) ? ($item['description'] ?? '') : '';
                $updatedAt = is_array($item) ? ($item['updated_at'] ?? '') : '';

                $customKeys[] = [
                    'key_name'      => $name,
                    'is_configured' => !empty($val),
                    'masked_value'  => ApiKeysMasker::maskValue($val),
                    'description'   => $desc,
                    'updated_at'    => $updatedAt,
                ];
            }
        }
        return $customKeys;
    }
}

